// components/Work.vue
<template>
  <a
    :href="url"
    class="relative flex flex-col p-4 m-0 transition duration-300 transform bg-center bg-cover rounded-lg cursor-pointer  md:items-center md:flex-row hover:bg-black dark:hover:bg-white hover:bg-opacity-5 dark:hover:bg-opacity-5"
    target="_blank"
  >
    <img
      class="object-cover h-40 rounded-md md:w-48 md:h-full"
      :src="`/projects/${img}.png`"
      alt="logo"
    />
    <div class="mt-4 md:pl-6 md:mt-0">
      <h2 class="text-2xl">{{ title }}</h2>
      <p class="m-0">{{ role }}</p>
      <p class="mt-2 text-xl leading-6 text-gray-800 line-clamp-2">
        {{ description }}
      </p>
    </div>
  </a>
</template>

<script>
export default {
  props: ["url", "img", "role", "title", "description"],
};
</script>

// components/Work.tsx
export const Work: React.FC<{
  href: string;
  img: string;
  role: string;
  title: string;
  description: string;
}> = ({ href, img, role, title, description }) => {
  return (
    <a href={href} target="_blank" rel="noreferrer" className="work">
      <img src={`/projects/${img}.png`} alt={title} />
      <div>
        <h1>{title}</h1>
        <p className="role">{role}</p>
        <p className="description">{description}</p>
      </div>
    </a>
  );
};
